---
promtail_version: "3.6.1"
promtail_arch: "arm64"
promtail_download_url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-{{ promtail_arch }}.zip"

promtail_host_label: "goldenrod"
promtail_loki_url: "https://loki.lajas.tech/loki/api/v1/push"
